default: &default
  adapter: <%= ENV['APP_DATABASE_ADAPTER'] %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['APP_DATABASE_USERNAME'] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
  host: <%= ENV['APP_DATABASE_HOST'] %>
  port: <%= ENV['APP_DATABASE_PORT'] %>

development:
  <<: *default
  database: <%= ENV['APP_DATABASE_DEV'] %>

test:
  <<: *default
  database: <%= ENV['APP_DATABASE_TEST'] %>

production:
  <<: *default
  database: rails-admin-production
  username: angelo
  password: Rails.application.credentials.dig(:production, :db_password)
